In [1]:
import geopandas as gpd
import pandas as pd
import numpy as np

### Generate a GeoDataFrame that covers the socialist housing developments

In [2]:
!ls /data/uscuni-ulce/additional_data/housing_estates_locations

HEs_delimitation.xlsx  ZSJ_2013.sbn	 ZSJ_2016.cpg  ZSJ_2016.shp
prague		       ZSJ_2013.sbx	 ZSJ_2016.dbf  ZSJ_2016.shp.xml
ZSJ_2013.cpg	       ZSJ_2013.shp	 ZSJ_2016.prj  ZSJ_2016.shx
ZSJ_2013.dbf	       ZSJ_2013.shp.xml  ZSJ_2016.sbn
ZSJ_2013.prj	       ZSJ_2013.shx	 ZSJ_2016.sbx

In [3]:
xcl = pd.read_excel('/data/uscuni-ulce/additional_data/housing_estates_locations/HEs_delimitation.xlsx')
xcl.columns

Index(['MUNICIPALITY CODE', 'MUNICIPALITY NAME', 'BSU CODE_2014',
       'BSU CODE6_2014', 'BSU NAME_CURRENT', 'poznámky', 'SOC HE',
       'SOC&POSTSOC HE', 'Unnamed: 8', 'BSU CODE_1974', 'BSU NAME_1974',
       'DELIMITATION OK?', 'BSU CODE_1980', 'ZSJ1980', 'DELIMITATION OK?.1',
       'BSU CODE_1992', 'BSU NAME_1992', 'DELIMITATION OK?.2', 'BSU CODE_2001',
       'BSU NAME_2001', 'DELIMITATION OK?.3', 'BSU CODE_2014.1',
       'BSU NAME_2014', 'DELIMITATION OK?.4'],
      dtype='object')

In [4]:
xcl

,MUNICIPALITY CODE,MUNICIPALITY NAME,BSU CODE_2014,BSU CODE6_2014,BSU NAME_CURRENT,poznámky,SOC HE,SOC&POSTSOC HE,Unnamed: 8,BSU CODE_1974,...,DELIMITATION OK?.1,BSU CODE_1992,BSU NAME_1992,DELIMITATION OK?.2,BSU CODE_2001,BSU NAME_2001,DELIMITATION OK?.3,BSU CODE_2014.1,BSU NAME_2014,DELIMITATION OK?.4
0,562335,Děčín,71610,7161,Boletice nad Labem,NaN,yes,yes,NaN,716.0,...,ok,71610.0,Boletice nad Labem,ok,71610.0,Boletice nad Labem,ok,71610,Boletice nad Labem,ok
1,582786,Brno,101540,10154,Vsetínská,NaN,yes,yes,NaN,1015.0,...,ok,101540.0,Vsetínská,ok,101540.0,Vsetínská,ok,101540,Vsetínská,ok
2,582786,Brno,102190,10219,Neumannova,NaN,yes,yes,NaN,1021.0,...,ok,102190.0,Neumannova,ok,102190.0,Neumannova,ok,102190,Neumannova,ok
3,582786,Brno,103160,10316,Kohoutovice-sever,NaN,yes,yes,NaN,1031.0,...,ok (merge with Kohoutovice-jih (303992),103160.0,Kohoutovice-sever,ok (merge with Kohoutovice-jih (303992),103160.0,Kohoutovice-sever,ok (merge with Kohoutovice-jih (303992),103160,Kohoutovice-sever,ok (merge with Kohoutovice-jih (303992)
4,582786,Brno,3039920,303992,Kohoutovice-jih,NaN,no,yes,NaN,1031.0,...,ok (merge with Kohoutovice-sever (010316),3039920.0,Kohoutovice-jih,ok (merge with Kohoutovice-sever (010316),3039920.0,Kohoutovice-jih,ok (merge with Kohoutovice-sever (010316),3039920,Kohoutovice-jih,ok (merge with Kohoutovice-sever (010316)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
614,569810,Hradec Králové,3282510,328251,Plachta,NaN,no,yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3282510,Plachta,ok
615,555134,Pardubice,3291260,329126,Nová Trnová,NaN,no,yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3291260,Nová Trnová,ok
616,554791,Plzeň,3293210,329321,Květná,NaN,no,yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3293210,Květná,ok
617,554782,Praha,3297460,329746,Nové Pitkovice,NaN,no,yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3297460,Nové Pitkovice,ok
618,554782,Praha,3297710,329771,Slunečný Vršek,NaN,no,yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3297710,Slunečný Vršek,ok

In [5]:
estates = gpd.read_file('/data/uscuni-ulce/additional_data/housing_estates_locations/ZSJ_2016.shp')
estates[['KOD_ZSJ', 'KOD_UTJ', 'KOD_KU', 'KOD_MOaMC','KOD_OBEC', 'KOD_ZUJ',
     'KOD_OKRES', 'KOD_LAU1',  'KOD_KRAJ', 'KOD_CZNUTS']]

,KOD_ZSJ,KOD_UTJ,KOD_KU,KOD_MOaMC,KOD_OBEC,KOD_ZUJ,KOD_OKRES,KOD_LAU1,KOD_KRAJ,KOD_CZNUTS
0,000019,600016,600016,None,554979,554979,40436,CZ0412,3051,CZ041
1,000027,600024,600024,None,554979,554979,40436,CZ0412,3051,CZ041
2,000035,600032,600032,None,535826,535826,40282,CZ0311,3034,CZ031
3,000043,600041,600041,None,581291,581291,40703,CZ0641,3115,CZ064
4,000051,600059,600059,None,547786,547786,40584,CZ0523,3085,CZ052
...,...,...,...,...,...,...,...,...,...,...
22500,391883,991881,991881,None,592935,592935,40754,CZ0646,3115,CZ064
22501,391891,991899,991899,None,592935,592935,40754,CZ0646,3115,CZ064
22502,391905,991902,991902,None,592935,592935,40754,CZ0646,3115,CZ064
22503,392316,990833,990833,None,555177,555177,40436,CZ0412,3051,CZ041
22504,392391,992399,992399,None,555690,555690,40436,CZ0412,3051,CZ041

In [6]:
# estates = gpd.read_file('/data/uscuni-ulce/additional_data/housing_estates_locations/ZSJ_2013.shp')
# estates[['KOD_ZSJ', 'KOD_UTJ', 'KOD_KU']]

In [7]:
estates['merge'] = estates['KOD_ZSJ'].astype(np.int64)

In [8]:
xcl

,MUNICIPALITY CODE,MUNICIPALITY NAME,BSU CODE_2014,BSU CODE6_2014,BSU NAME_CURRENT,poznámky,SOC HE,SOC&POSTSOC HE,Unnamed: 8,BSU CODE_1974,...,DELIMITATION OK?.1,BSU CODE_1992,BSU NAME_1992,DELIMITATION OK?.2,BSU CODE_2001,BSU NAME_2001,DELIMITATION OK?.3,BSU CODE_2014.1,BSU NAME_2014,DELIMITATION OK?.4
0,562335,Děčín,71610,7161,Boletice nad Labem,NaN,yes,yes,NaN,716.0,...,ok,71610.0,Boletice nad Labem,ok,71610.0,Boletice nad Labem,ok,71610,Boletice nad Labem,ok
1,582786,Brno,101540,10154,Vsetínská,NaN,yes,yes,NaN,1015.0,...,ok,101540.0,Vsetínská,ok,101540.0,Vsetínská,ok,101540,Vsetínská,ok
2,582786,Brno,102190,10219,Neumannova,NaN,yes,yes,NaN,1021.0,...,ok,102190.0,Neumannova,ok,102190.0,Neumannova,ok,102190,Neumannova,ok
3,582786,Brno,103160,10316,Kohoutovice-sever,NaN,yes,yes,NaN,1031.0,...,ok (merge with Kohoutovice-jih (303992),103160.0,Kohoutovice-sever,ok (merge with Kohoutovice-jih (303992),103160.0,Kohoutovice-sever,ok (merge with Kohoutovice-jih (303992),103160,Kohoutovice-sever,ok (merge with Kohoutovice-jih (303992)
4,582786,Brno,3039920,303992,Kohoutovice-jih,NaN,no,yes,NaN,1031.0,...,ok (merge with Kohoutovice-sever (010316),3039920.0,Kohoutovice-jih,ok (merge with Kohoutovice-sever (010316),3039920.0,Kohoutovice-jih,ok (merge with Kohoutovice-sever (010316),3039920,Kohoutovice-jih,ok (merge with Kohoutovice-sever (010316)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
614,569810,Hradec Králové,3282510,328251,Plachta,NaN,no,yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3282510,Plachta,ok
615,555134,Pardubice,3291260,329126,Nová Trnová,NaN,no,yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3291260,Nová Trnová,ok
616,554791,Plzeň,3293210,329321,Květná,NaN,no,yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3293210,Květná,ok
617,554782,Praha,3297460,329746,Nové Pitkovice,NaN,no,yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3297460,Nové Pitkovice,ok
618,554782,Praha,3297710,329771,Slunečný Vršek,NaN,no,yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3297710,Slunečný Vršek,ok

In [9]:
estates

,OBJECTID,KOD_ZSJ,NAZ_ZSJ,KOD_UTJ,NAZ_UTJ,KOD_KU,NAZ_KU,KOD_MOaMC,NAZ_MOaMC,KOD_OBEC,...,NAZ_LAU1,KOD_KRAJ,KOD_CZNUTS,NAZ_CZNUTS,SX,SY,SHAPE_Leng,SHAPE_Area,geometry,merge
0,1,000019,Abertamy,600016,Abertamy,600016,Abertamy,None,None,554979,...,Karlovy Vary,3051,CZ041,Karlovarský kraj,-850723.020041,-9.954003e+05,14334.505928,4.495815e+06,"POLYGON ((-851110.2 -993590.8, -851110 -993633...",19
1,2,000027,Hřebečná,600024,Hřebečná,600024,Hřebečná,None,None,554979,...,Karlovy Vary,3051,CZ041,Karlovarský kraj,-850086.144023,-9.931472e+05,10639.455512,4.201627e+06,"POLYGON ((-848530.42 -992326.69, -848568.45 -9...",27
2,3,000035,Adamov,600032,Adamov u Českých Budějovic,600032,Adamov u Českých Budějovic,None,None,535826,...,České Budějovice,3034,CZ031,Jihočeský kraj,-750632.681550,-1.163900e+06,3249.497744,2.943796e+05,"POLYGON ((-750760.81 -1163589.91, -750753.95 -...",35
3,4,000043,Adamov-střed,600041,Adamov,600041,Adamov,None,None,581291,...,Blansko,3115,CZ064,Jihomoravský kraj,-592727.262885,-1.149301e+06,11825.584393,9.482951e+05,"POLYGON ((-592245.55 -1148394.97, -592201.4 -1...",43
4,5,000051,Dolní Adršpach,600059,Dolní Adršpach,600059,Dolní Adršpach,None,None,547786,...,Náchod,3085,CZ052,Královéhradecký kraj,-616037.764016,-9.994413e+05,17048.649760,1.165216e+07,"POLYGON ((-616230.79 -996898.41, -616231.9 -99...",51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22500,22501,391883,Osina,991881,Osina,991881,Osina,None,None,592935,...,Vyškov,3115,CZ064,Jihomoravský kraj,-569855.639995,-1.138168e+06,29532.667221,2.927643e+07,"POLYGON ((-567707.44 -1134907.03, -567706.36 -...",391883
22501,22502,391891,Pulkava,991899,Pulkava,991899,Pulkava,None,None,592935,...,Vyškov,3115,CZ064,Jihomoravský kraj,-567270.195946,-1.142738e+06,17026.650968,8.257026e+06,"POLYGON ((-565924.44 -1141141.34, -565925.89 -...",391891
22502,22503,391905,Žbánov,991902,Žbánov,991902,Žbánov,None,None,592935,...,Vyškov,3115,CZ064,Jihomoravský kraj,-572394.441436,-1.133052e+06,37913.661082,3.406010e+07,"POLYGON ((-571572.12 -1130286.25, -571552.07 -...",391905
22503,22504,392316,Korunní,990833,Doupov u Hradiště,990833,Doupov u Hradiště,None,None,555177,...,Karlovy Vary,3051,CZ041,Karlovarský kraj,-835904.676667,-1.005037e+06,45025.316365,2.488600e+07,"POLYGON ((-832343.5 -999779.72, -832330.57 -99...",392316
22504,22505,392391,Valeč u Hradiště,992399,Valeč u Hradiště,992399,Valeč u Hradiště,None,None,555690,...,Karlovy Vary,3051,CZ041,Karlovarský kraj,-824784.438378,-1.020060e+06,13191.510325,6.492396e+06,"POLYGON ((-823913.15 -1019071.79, -823782.5 -1...",392391

In [10]:
merged = pd.merge(estates, xcl[['BSU CODE6_2014', 'SOC HE', 'SOC&POSTSOC HE' ]], left_on='merge', right_on='BSU CODE6_2014')

In [11]:
merged[merged['SOC HE'] == 'yes'].shape

(428, 28)

In [12]:
merged = merged[merged['SOC&POSTSOC HE'] == 'yes']

In [13]:
merged.shape

(576, 28)

In [14]:
cz_soc_housing = merged.to_crs(epsg=3035)

### Process all buildings, in all regions that have socialist housing

In [15]:
from libpysal.graph import Graph
regions_datadir = "/data/uscuni-ulce/"
simplfied_buildings_dir = '/data/uscuni-ulce/processed_data/simplified_buildings/'
buildings_dir = '/data/uscuni-ulce/processed_data/buildings/'

In [16]:
region_hulls = gpd.read_parquet(
        regions_datadir + "regions/" + "cadastre_regions_hull.parquet"
    )
inp, _ = cz_soc_housing.sindex.query(region_hulls.geometry, predicate='intersects')
czech_regions = region_hulls.iloc[np.unique(inp)]

In [21]:
czech_regions.index.values

array([ 55835,  61183,  61187,  63756,  64463,  66593,  67156,  67803,
        69333,  72507,  73735,  75472,  75642,  83538,  84297,  84962,
        93167,  97978, 100210, 102127, 103882, 105090, 107131])

In [139]:
%%time
for region_id,_ in czech_regions.iterrows():
    
    ## read region building polygons
    buildings = gpd.read_parquet(simplfied_buildings_dir + f"buildings_{region_id}.parquet")
    buildings['area'] = buildings.area
    buildings['perimeter'] = buildings.length

    ### mark buildings in socialist housing
    _, blg_ix = buildings.sindex.query(cz_soc_housing.geometry, predicate="intersects")
    relevant = pd.Series(0, index=buildings.index, dtype=bool)
    relevant.iloc[np.unique(blg_ix)] = True

    # create a contiguity graph for the  buildings in socialist housing polygons
    contig = Graph.build_fuzzy_contiguity(buildings[relevant], buffer=1e-3)

    # get potetial socialist housing buildings
    min_area = 180
    min_perimeter = 55
    mask = (buildings['area'] > min_area) & (buildings['perimeter'] > min_perimeter) & relevant
    masked = buildings[mask].copy()

    ## merge potential socialist housing buildings, based on buffered graph contiguity
    masked.geometry = masked.buffer(1e-3)
    subgraph = contig.subgraph(masked.index)
    merged = masked.dissolve(subgraph.component_labels).explode()

    # add the rest of the data to the merged subset and save
    fixed = pd.concat([buildings[~relevant], merged], ignore_index=True)
    assert not fixed.index.duplicated().any()
    fixed.drop(columns=['area', 'perimeter']).to_parquet(buildings_dir + f"buildings_{region_id}.parquet")

CPU times: user 14.6 s, sys: 1.81 s, total: 16.4 s
Wall time: 16.1 s